# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f72679a0c9fea963918627aff83979087b1757f63e32097e1290211069ec2f7d08d04edde65586e0597bd4f2d3db643c535c44b7d6fceed2ef8a36f7aee756e8

test:
  secret_key_base: 2a4f9534262bf45ff8d8a000c63fb4c8da994fce1ac59da8e4f968f4fea526ad071e2ce371bbab7f8cc1b899afa519f8d805ab90eff03b5b760a97964bb23f71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
